// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pressur.Data.Context;

#nullable disable

namespace Pressur.Data.Migrations
{
    [DbContext(typeof(PressurContext))]
    [Migration("20250124164655_nome-da-migration-projeto")]
    partial class nomedamigrationprojeto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Pressur.Domain.Entities.Cadastros.CoresDeVeiculo.CorDeVeiculo", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<string>("CodigoEmpresa")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id", "CodigoEmpresa");

                    b.ToTable("CorDeVeiculo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            CodigoEmpresa = "default",
                            Nome = "Prata"
                        },
                        new
                        {
                            Id = (short)2,
                            CodigoEmpresa = "default",
                            Nome = "Preto"
                        },
                        new
                        {
                            Id = (short)3,
                            CodigoEmpresa = "default",
                            Nome = "Vermelho"
                        },
                        new
                        {
                            Id = (short)4,
                            CodigoEmpresa = "default",
                            Nome = "Verde"
                        },
                        new
                        {
                            Id = (short)5,
                            CodigoEmpresa = "default",
                            Nome = "Laranja"
                        },
                        new
                        {
                            Id = (short)6,
                            CodigoEmpresa = "default",
                            Nome = "Azul"
                        },
                        new
                        {
                            Id = (short)7,
                            CodigoEmpresa = "default",
                            Nome = "Branco"
                        },
                        new
                        {
                            Id = (short)8,
                            CodigoEmpresa = "default",
                            Nome = "Cinza"
                        },
                        new
                        {
                            Id = (short)9,
                            CodigoEmpresa = "default",
                            Nome = "Marrom"
                        },
                        new
                        {
                            Id = (short)10,
                            CodigoEmpresa = "default",
                            Nome = "Bege"
                        },
                        new
                        {
                            Id = (short)11,
                            CodigoEmpresa = "default",
                            Nome = "Dourado"
                        },
                        new
                        {
                            Id = (short)12,
                            CodigoEmpresa = "default",
                            Nome = "Rosa"
                        },
                        new
                        {
                            Id = (short)13,
                            CodigoEmpresa = "default",
                            Nome = "Roxo"
                        });
                });

            modelBuilder.Entity("Pressur.Domain.Entities.Empresas.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("CodigoEmpresa")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id", "CodigoEmpresa");

                    b.ToTable("Empresa", (string)null);
                });

            modelBuilder.Entity("Pressur.Domain.Entities.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CodigoEmpresa")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Login");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Pressur.Domain.Entities.Empresas.Empresa", b =>
                {
                    b.OwnsOne("Pressur.Domain.ValueObjects.CnpjObject.Cnpj", "Cnpj", b1 =>
                        {
                            b1.Property<Guid>("EmpresaId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("EmpresaCodigoEmpresa")
                                .HasColumnType("varchar(12)");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(14)
                                .HasColumnType("varchar(14)")
                                .HasColumnName("Cnpj");

                            b1.HasKey("EmpresaId", "EmpresaCodigoEmpresa");

                            b1.ToTable("Empresa");

                            b1.WithOwner()
                                .HasForeignKey("EmpresaId", "EmpresaCodigoEmpresa");
                        });

                    b.Navigation("Cnpj")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
